#Pod creation
apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod
  labels: 
    app: myapp
spec: 
  containers:
    - name: nginx-container
      image: nginx
  
# Replicaset
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: 
      name: myapp-pod
      labels: 
        app: myapp
    spec: 
      containers:
        - name: nginx-container
          image: nginx
        
  replicas: 4
  selector:
    matchLabel:
      app: myapp 

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: 
      name: myapp-pod
      labels: 
        app: myapp
    spec: 
      containers:
        - name: nginx-container
          image: nginx
        
  replicas: 4
  selector:
    matchLabels:
      app: myapp

#Service
apiVersion: v1
kind: Service
metadata:
  name: my-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort:  30008
  selector: 
    app: myapp


########VotingApp###########

#Pod-voting-app
apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80

#Pod-worker
apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-worker-app
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker

#Pod-result-app
apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-result-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80

#Pod-redis
apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
  labels:
    name: redis-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379

#Pod-Postgres
apiVersion: v1
kind: Pod
metadata: 
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432

#Services - redis
apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    name: redis-service
    app: demo-redis-app
spec:
  ports:
      port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-redis-app 

#Services - postgres-db
apiVersion: v1
kind: Service
metadata: 
  name: db
  labels:
    name: db-service
    app: demo-redis-app
spec:
  ports:
      port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-redis-app 

