apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.mysql.name }}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.mysql.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.mysql.storage }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.wordpress.name }}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.wordpress.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.wordpress.storage }}
