
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.wordpress.service.name }}
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.wordpress.service.port }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
  type: NodePort