apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port}}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}