apiVersion: v1
kind: Service
metadata: 
  name: voting-service
  labels:
    app: demo-voting-app
    name: voting-service
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
      