apiVersion: v1
kind: Service
metadata: 
  name: worker-service
  labels:
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    name: worker-app-pod
    app: demo-worker-app
  ports:
    - port: 80
      targetPort: 80
      