apiVersion: v1
kind: Service
metadata: 
  name: worker-service
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-worker-app
  ports:
    - port: 80
      targetPort: 30001
      